### ISSUE TITLE
The pipe 'emojis' could not be found

### ISSUE THREAD

**Issue by narendraraghuwanshi** [AhsanAyaz/ng2-emoji#10]
`webpack-internal:///./src/main.ts:11 Error: Template parse errors:
The pipe 'emojis' could not be found ("
                      <div class="message">
                        <p   class="message-container" [ERROR ->][innerHTML]="message.content | emojis"> </p>
                      </div>
                      <div "): ng:///ChatModule/ChatComponent.html@76:55
    at syntaxError (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:684)
    at TemplateParser.parse (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:24547)
    at JitCompiler._parseTemplate (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:33975)
    at JitCompiler._compileTemplate (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:33950)
    at eval (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:33852)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:33852)
    at eval (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:33722)
    at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:392)
    at Zone.run (webpack-internal:///./node_modules/zone.js/dist/zone.js:142)`

**Comment by AhsanAyaz** [comment]
Hi @narendraraghuwanshi 
Could you please mention what version of Angular you are using.
If you can reproduce this issue on https://stackblitz.com/ , that'll be awesome!

**Comment by narendraraghuwanshi** [comment]
I am using angular 5

`import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { MatButtonModule, MatCardModule, MatInputModule, MatSnackBarModule, MatToolbarModule } from '@angular/material';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { EditorModule } from '@tinymce/tinymce-angular';
import { FileUploadModule } from 'primeng/components/fileupload/fileupload';
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { NavComponent } from './nav/nav.component';
import { RegistrationComponent } from './registration/registration.component';
import { LoginComponent } from './login/login.component';
import { ProfileComponent } from './profile/profile.component';
import { ProfileService } from './profile.service';
import { AuthService } from './auth.service';
import { AuthGuard } from './auth.guard';
import { PostService} from './models/post.service';
import { EmojiPickerModule} from 'ng-emoji-picker';
import { VgCoreModule} from 'videogular2/core';
import { VgControlsModule} from 'videogular2/controls';
import { VgOverlayPlayModule} from 'videogular2/overlay-play';
import { VgBufferingModule} from 'videogular2/buffering';
import { Ng2CarouselamosModule} from 'ng2-carouselamos';
import { ChatModule } from './chat/chat.module';
import { SharedModule } from './shared/shared.module';
import { ChatComponent} from './chat/chat.component';
import { ProfileEditComponent } from './profile-edit/profile-edit.component';
import { ImageCropperModule } from 'ngx-image-cropper';
import { Ng2EmojiModule } from 'ng2-emoji';

const myRoots: Routes = [
  { path: '', component: HomeComponent, pathMatch: 'full' , canActivate: [AuthGuard]},
  { path: 'register', component: RegistrationComponent },
  { path: 'login', component: LoginComponent},
  { path: 'app-chat', component: ChatComponent, canActivate: [AuthGuard]},
  { path: 'home', component: HomeComponent, canActivate: [AuthGuard]},
  { path: 'profile', component: ProfileComponent, canActivate: [AuthGuard]},
  { path: 'profile/edit', component: ProfileEditComponent, canActivate: [AuthGuard]}
];

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    NavComponent,
    RegistrationComponent,
    LoginComponent,
    ProfileComponent,
    ProfileEditComponent,

  ],
  imports: [
    BrowserModule,
      BrowserAnimationsModule,
      HttpClientModule,
      FormsModule,
      ReactiveFormsModule,
     MatButtonModule,
      MatCardModule,
      MatInputModule,
      MatSnackBarModule,
      MatToolbarModule,
      FileUploadModule ,
      EditorModule,
      VgCoreModule,
      Ng2CarouselamosModule,
      VgControlsModule,
      VgOverlayPlayModule,
      VgBufferingModule,
      EmojiPickerModule,
      ChatModule,
      SharedModule,
      ImageCropperModule,
      Ng2EmojiModule.forRoot(),
      RouterModule.forRoot(myRoots)
  ],
  providers: [AuthService, AuthGuard, ProfileService,PostService],
  bootstrap: [AppComponent]
})


export class AppModule {

}
`

**Comment by narendraraghuwanshi** [comment]
I dont import module on my componnt

When i import this on home.component.ts Its Solve
