### ISSUE TITLE
Adding an angular2+ (angular-cli) example

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/ng2-emoji#5]
Adding an example folder with angular code using `ng2-emoji`. 
We'll be using travisCI later to deploy this to `gh-pages` as a demo

**Comment by jcjc712** [comment]
Hello, I will work with the example folder.

**Comment by AhsanAyaz** [comment]
Sure @jcjc712

**Comment by jcjc712** [comment]
@AhsanAyaz done.
https://github.com/AhsanAyaz/ng2-emoji/pull/6

**Comment by AhsanAyaz** [comment]
https://github.com/AhsanAyaz/ng2-emoji/pull/6 closes this issue. 
Thanks to @jcjc712
